
export const FETCH_JOB_BOARD_REQUEST = "FETCH_JOB_BOARD_REQUEST";
export const FETCH_JOB_BOARD_SUCCESS = "FETCH_JOB_BOARD_SUCCESS";
export const FETCH_JOB_BOARD_FAILURE = "FETCH_JOB_BOARD_FAILURE";

export const SET_FILTER = "SET_FILTER";
